# Generated by Django 4.1.7 on 2023-02-16 02:12

from django.db import migrations, models
import django.db.models.deletion
import info_edit.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CityArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area_name_text", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="CityName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_name_text",
                    models.CharField(max_length=10, verbose_name="市区町村"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_text", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="MenuImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=info_edit.models.make_menu_upload_path,
                        variations={"large": (600, 400), "thumbnail": (150, 100)},
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name_text",
                    models.CharField(max_length=20, verbose_name="店名"),
                ),
                (
                    "pub_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日時"),
                ),
                ("mod_date", models.DateTimeField(auto_now=True, verbose_name="更新日時")),
                (
                    "restaurant_address",
                    models.CharField(max_length=200, verbose_name="所在地"),
                ),
                (
                    "restaurant_comment",
                    models.CharField(blank=True, max_length=300, verbose_name="コメント"),
                ),
                ("image_num", models.IntegerField(default=0)),
                (
                    "city_area",
                    models.ManyToManyField(to="info_edit.cityarea", verbose_name="エリア"),
                ),
                (
                    "restaurant_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info_edit.cityname",
                        verbose_name="市区町村",
                    ),
                ),
                (
                    "restaurant_genre",
                    models.ManyToManyField(to="info_edit.genre", verbose_name="ジャンル"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_name_text",
                    models.CharField(max_length=100, verbose_name="料理名"),
                ),
                (
                    "menu_comment_text",
                    models.CharField(max_length=300, verbose_name="コメント"),
                ),
                (
                    "menu_price",
                    models.IntegerField(blank=True, default=0, verbose_name="価格"),
                ),
                ("image_num", models.IntegerField(default=0)),
                (
                    "sub_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info_edit.restaurant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RestaurantImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    stdimage.models.StdImageField(
                        blank=True,
                        force_min_size=False,
                        null=True,
                        upload_to=info_edit.models.make_upload_path,
                        variations={"large": (600, 400), "thumbnail": (150, 100)},
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=20)),
                (
                    "sub_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="info_edit.restaurant",
                    ),
                ),
            ],
        ),
    ]
