# Generated by Django 4.1.7 on 2023-02-16 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("info_edit", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="menuimage",
            name="sub_menu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="info_edit.restaurantmenu",
            ),
        ),
        migrations.AddField(
            model_name="cityarea",
            name="city_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="info_edit.cityname"
            ),
        ),
    ]
