# Generated by Django 4.1.7 on 2023-02-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info_edit", "0004_alter_menuimage_sub_menu_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="max_menu_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restaurantmenu",
            name="menu_id",
            field=models.IntegerField(default=0, verbose_name="料理ID"),
        ),
    ]
